"""Measured XGO-Lite2 actuator constants (GENERATED — do not hand-edit).

Generated by scripts/apply_servo_fit.py on 2026-07-14T15:38:28
from servo_fit_v3.json (fit created 2026-07-14T15:22:15, sessions: ['/home/dvv/dev/bots/servo_id_data/servo_id/2026-07-13_18-07-30_stand', '/home/dvv/dev/bots/servo_id_data/servo_id/2026-07-13_18-04-06_stand']).

Stage-1 servo fit: per-joint MJCF dynamics, PD gains, torque-speed clamp
and the global command delay. See the fit report next to the fit.json for
sim-vs-real validation. Regenerate with:
  PYTHONPATH=. .venv/bin/python scripts/apply_servo_fit.py servo_fit_v3.json \
    --write-cfg src/tasks/velocity/config/xgolite/measured_actuators.py
"""

# joint -> dict(damping, armature, frictionloss, kp, kd,
#               qd_knee, qd_max, deadband)
# qd_knee/qd_max parameterize the fitted piecewise torque-speed curve
# (driving torque flat at TAU_MAX up to qd_knee, linear taper to zero at
# qd_max) consumed by the knee-form TorqueSpeedClamp.
# deadband (fitted lost-motion nominal, rad) is carried for reference: the
# v19 preset randomizes the deadband WIDE instead of pinning these — the
# measured small-amplitude delivery of 0.79-0.93 implies up to ~0.02 rad
# effective lost motion (dynamic hysteresis the model cannot express).
MEASURED_JOINTS = {
  'fl_hip': {'damping': 0.011143, 'armature': 0.0, 'frictionloss': 0.000461, 'kp': 39.7129, 'kd': 0.0068, 'qd_knee': 3.6468, 'qd_max': 12.0939, 'deadband': 0.0006},
  'fl_thigh': {'damping': 0.011143, 'armature': 0.0, 'frictionloss': 0.000461, 'kp': 39.7129, 'kd': 0.0068, 'qd_knee': 3.6468, 'qd_max': 12.0939, 'deadband': 0.0081},
  'fl_calf': {'damping': 0.011143, 'armature': 0.0, 'frictionloss': 0.000461, 'kp': 39.7129, 'kd': 0.0068, 'qd_knee': 3.6468, 'qd_max': 12.0939, 'deadband': 0.0052},
  'fr_hip': {'damping': 0.011143, 'armature': 0.0, 'frictionloss': 0.000461, 'kp': 39.7129, 'kd': 0.0068, 'qd_knee': 3.6468, 'qd_max': 12.0939, 'deadband': 0.0005},
  'fr_thigh': {'damping': 0.011143, 'armature': 0.0, 'frictionloss': 0.000461, 'kp': 39.7129, 'kd': 0.0068, 'qd_knee': 3.6468, 'qd_max': 12.0939, 'deadband': 0.0012},
  'fr_calf': {'damping': 0.011143, 'armature': 0.0, 'frictionloss': 0.000461, 'kp': 39.7129, 'kd': 0.0068, 'qd_knee': 3.6468, 'qd_max': 12.0939, 'deadband': 0.0059},
  'bl_hip': {'damping': 0.011143, 'armature': 0.0, 'frictionloss': 0.000461, 'kp': 39.7129, 'kd': 0.0068, 'qd_knee': 3.6468, 'qd_max': 12.0939, 'deadband': 0.0077},
  'bl_thigh': {'damping': 0.011143, 'armature': 0.0, 'frictionloss': 0.000461, 'kp': 39.7129, 'kd': 0.0068, 'qd_knee': 3.6468, 'qd_max': 12.0939, 'deadband': 0.0053},
  'bl_calf': {'damping': 0.011143, 'armature': 0.0, 'frictionloss': 0.000461, 'kp': 39.7129, 'kd': 0.0068, 'qd_knee': 3.6468, 'qd_max': 12.0939, 'deadband': 0.0031},
  'br_hip': {'damping': 0.011143, 'armature': 0.0, 'frictionloss': 0.000461, 'kp': 39.7129, 'kd': 0.0068, 'qd_knee': 3.6468, 'qd_max': 12.0939, 'deadband': 0.0074},
  'br_thigh': {'damping': 0.011143, 'armature': 0.0, 'frictionloss': 0.000461, 'kp': 39.7129, 'kd': 0.0068, 'qd_knee': 3.6468, 'qd_max': 12.0939, 'deadband': 0.0024},
  'br_calf': {'damping': 0.011143, 'armature': 0.0, 'frictionloss': 0.000461, 'kp': 39.7129, 'kd': 0.0068, 'qd_knee': 3.6468, 'qd_max': 12.0939, 'deadband': 0.0028},
}

TAU_MAX = 0.22  # N*m, pinned fit anchor (== XML forcerange)

# Class means (for the scalar knee-form TorqueSpeedClamp API).
MEASURED_QD_KNEE = 3.6468
MEASURED_QD_MAX = 12.0939

# Global command delay (firmware receipt -> actuation) and the
# recommended per-servo delay DR range (measured onset spread +/-22 ms),
# in physics steps at 2.0 ms.
MEASURED_DELAY_MS = 42.95
DELAY_MIN_LAG_STEPS = 10
DELAY_MAX_LAG_STEPS = 32


def apply_measured_joint_dynamics(spec) -> None:
  """Write fitted MJCF joint fields + PD gains into an MjSpec in place.

  Call on the spec returned by ``xgolite_constants.get_spec()`` before
  compilation. Position actuator convention: gainprm[0] = kp,
  biasprm = (0, -kp, -kd).
  """
  for joint, p in MEASURED_JOINTS.items():
    j = spec.joint(joint + "_joint")
    j.damping = p["damping"]
    j.armature = p["armature"]
    j.frictionloss = p["frictionloss"]
    a = spec.actuator(joint + "_joint")
    a.gainprm[0] = p["kp"]
    a.biasprm[1] = -p["kp"]
    a.biasprm[2] = -p["kd"]


def enable_measured_torque_speed_clamp(cfg) -> None:
  """Wire the knee-form clamp with measured class-mean parameters.

  The clamp API is scalar (one tau_max/qd_knee/qd_max for all joints);
  per-joint values live in MEASURED_JOINTS for a future per-joint clamp.
  """
  from src.tasks.velocity.config.xgolite.sim_fidelity import (
    enable_torque_speed_clamp,
  )

  enable_torque_speed_clamp(
    cfg,
    tau_max=TAU_MAX,
    qd_knee=MEASURED_QD_KNEE,
    qd_max=MEASURED_QD_MAX,
  )


def measured_delay_actuator_cfg():
  """DelayedActuatorCfg with the measured delay DR range."""
  import dataclasses

  from src.assets.robots.xgolite.xgolite_constants import (
    XGOLITE_XML_ACTUATOR,
  )

  return dataclasses.replace(
    XGOLITE_XML_ACTUATOR,
    delay_min_lag=DELAY_MIN_LAG_STEPS,
    delay_max_lag=DELAY_MAX_LAG_STEPS,
  )
